### ISSUE TITLE
Ability to add disk encryption

### ISSUE THREAD

**Issue by nobaraos12** [Vanilla-OS/vanilla-installer#102]
The ability to add disk encryption at the installer would be nice, this should really be a standard feature for an linux distro....

**Comment by mirkobrombin** [comment]
Do not use uppercase.

**Comment by Odi-3** [comment]
My suggestion is to make a Plymouth screen without text. The lock image may be enough to suggest that a password must be entered, as in Fedora.

**Comment by axel-1267** [comment]
This is an absolute needed feature. Thanks Mirko and the vanilla community for the amazing project.

**Comment by Schmensch** [comment]
How well does ABRoot work with encrypted root? Did anybody try this yet?

**Comment by Schmensch** [comment]
Alternatively you could just encrypt the user partition (`/home/`) or encrypt each users home directory (/home/user1, /home/user2) individually with something like systemd-homed, eCryptFS or gocryptfs.

**Comment by Schmensch** [comment]
I tried it, and it works (there is one big caveat though):

- Install ecryptfs-utils (`sudo abroot exec apt install ecryptfs-utils`)
- Create a temporary user with admin privileges
- Log out & log in to the temporary and make sure the user whose files you're encrypting doesn't have any processes running (`ps -U <username>`)
- With the temporary user, run:
  - `sudo modprobe ecryptfs`
  - `ecryptfs-migrate-home -u <username>`
- Without rebooting, log back into the user whose files you've just encrypted.

The one caveat:

apx doesn't work. I tracked this issue down to podman not being able to work within eCryptFS.

**Comment by Schmensch** [comment]
I'm gonna try systemd-homed when I'm back home.

**Comment by hperrin** [comment]
Not having disk encryption is a deal breaker for me, as it would be for any business that has trade secrets stored on employees' laptops.

If someone steals my laptop, I need them to not be able to access all of my company's private source code and my private SSH keys.

**Comment by kbdharun** [comment]
Update on this, Disk Encryption support has been added to [Albius](https://github.com/Vanilla-OS/Albius) our installer backend and the installer by @matbme [the changes are present in the `albius` branch but it will soon be merged with the `main` branch ]. Orchid will have support for it officially in the next release.

**Comment by matbme** [comment]
As of Orchid, Vanilla OS will support encrypting the `/var` directory, which contains everything not pulled directly from the base system image. This means that any personal files will be encrypted, including the entire `/home` directory and any new or modified files in `/etc`, `/var` and `/opt`.

In the future we hope to add an option to encrypt the root partitions as well, but we'll open a separate issue for that.

**Comment by hperrin** [comment]
> including the entire `/home` directory and any new or modified files in `/etc`, `/var` and `/opt`.


I'm assuming the answer is yes, but just to be sure, does this include the `/root` directory?

**Comment by dddw** [comment]
when will this be merged in the alpha build?

**Comment by matbme** [comment]
It already is

**Comment by dddw** [comment]
ah so with what passphrase are the disks encrypted...? was never asked for it in the alpha installer

**Comment by kbdharun** [comment]
> ah so with what passphrase are the disks encrypted...? was never asked for it in the alpha installer


Hmm, the FDE passphrase is indeed asked in the installer (on the alpha builds), are you sure you aren't using the Kinetic ISO instead of the Orchid one (I am pretty sure this is the case, or it is possible you might have missed the panel when going through the installation steps)?

**Comment by dddw** [comment]
you are right! apparently I download the Kinetic ISO early and DD'd that to the flashdisk. 
sorry for the mixup
