### ISSUE TITLE
Select computer hostname

### ISSUE THREAD

**Issue by matbme** [Vanilla-OS/vanilla-installer#122]
Right now the system always defaults to `vanilla` as the hostname. We should add a field in the installer to allow the user to set a different name.

Some points that we have to keep in mind:
- Hostnames cannot have upper-cased letters nor spaces
- We need to make sure Distinst properly configures `/etc/hostname` and `/etc/hosts` to avoid problems after installation

**Comment by Muqtxdir** [comment]
shouldn't this go under first-setup if we are going the oem route?

**Comment by mirkobrombin** [comment]
Yes

**Comment by matbme** [comment]
> shouldn't this go under first-setup if we are going the oem route?

Makes sense, I'll close it here and re-create it there.
