### ISSUE TITLE
No "Manual Partition" Option - NVME SSD

### ISSUE THREAD

**Issue by ebolaboi** [Vanilla-OS/vanilla-installer#135]
I am attempting to install natively on my PC, which uses an NVME SSD. I have heard that NVME disks sometimes have issues with certain linux distros, but I am not sure if this is the case or there is something wrong with my installer iso.

![Screenshot from 2023-02-18 14-52-46](https://user-images.githubusercontent.com/61773927/219872396-94607968-d976-44df-b675-898c1d32fe8e.png)

**Comment by kbdharun** [comment]
Manual partitioning was added to the installer just yesterday at https://github.com/Vanilla-OS/vanilla-installer/pull/121, we have been testing it in various hardware for the past week. 

It will be available in the installer with the next release.
