### ISSUE TITLE
Incorrect use of BTRFS

### ISSUE THREAD

**Issue by bleonard252** [Vanilla-OS/vanilla-installer#157]
Using manual partitioning, it appears that A and B root (which are configured, perhaps erroneously, as BTRFS partitions) as well as /home use the root partition directly, which makes Timeshift's BTRFS mode incompatible with VanillaOS on a fresh install.

Relevant lines from `sudo mount`:
```
/dev/nvme0n1p4 on / type btrfs (rw,relatime,ssd,space_cache=v2,subvolid=5,subvol=/)
/dev/nvme0n1p4 on /.system/usr type btrfs (ro,relatime,ssd,space_cache=v2,subvolid=5,subvol=/)
/dev/nvme0n1p4 on /opt type btrfs (rw,relatime,ssd,space_cache=v2,subvolid=5,subvol=/)
/dev/nvme0n1p4 on /var type btrfs (rw,relatime,ssd,space_cache=v2,subvolid=5,subvol=/)
/dev/nvme0n1p5 on /home type btrfs (rw,relatime,ssd,space_cache=v2,subvolid=5,subvol=/)
```

Running `sudo btrfs subvolume list /home` (or with any of the other mount points listed above) returns no information at all.

The expected behavior is that `/` is mounted to subvol `@` and `/home` is mounted to subvol `@home`.

**Comment by Khayasen** [comment]
I believe that expected behaviour of yours is Ubuntu's default partitioning, meanwhile other OS'es like Fedora doesn't follow the same behaviour, so maybe Vanilla also does not do that.

(Timeshift is made for Linux Mint which follows Ubuntu's partitioning, while Vanilla has to make their own partition because of ABRoot.)

**Comment by bleonard252** [comment]
VanillaOS is Ubuntu-based and promotes Timeshift in First Setup, so it makes sense for it to be compatible.

**Comment by lavilao** [comment]
check this https://github.com/Vanilla-OS/os/issues/98#issuecomment-1418264709

**Comment by taukakao** [comment]
It's not incorrect. Timeshift just uses the Ubuntu layout, which we don't. 
Timeshift will also not be included by default anymore.
