### ISSUE TITLE
Hide filesystem dropdown from unselected partitions

### ISSUE THREAD

**Issue by matbme** [Vanilla-OS/vanilla-installer#159]
When selecting a partition that allows changing the filesystem (e.g. home), we should hide the dropdown from partitions that are not selected.

Related image:
![image](https://user-images.githubusercontent.com/48367298/225342490-5b2ce55b-4b23-49ca-8377-10730fa69b20.png)

**Comment by mirkobrombin** [comment]
Is this still a valid issue referencing https://github.com/Vanilla-OS/vanilla-installer/pull/177 ?

**Comment by matbme** [comment]
Fixed in #177, closing.
