### ISSUE TITLE
No character limit on user display name?

### ISSUE THREAD

**Issue by HappiePlant** [Vanilla-OS/vanilla-installer#18]
It seems there's no character limit for the display name when creating a user in the Vanilla Installer.
![image](https://user-images.githubusercontent.com/46526955/199822049-a69b34a4-055a-4679-bcc0-ed4a0c361270.png)

**Comment by HappiePlant** [comment]
When I try to login after installation it doesn't display my display name and I can't log in. :P
https://user-images.githubusercontent.com/46526955/199822916-81a1c4e0-f36b-4597-bb30-4348c521d7d2.mp4

**Comment by mirkobrombin** [comment]
Dude



---

planning a fix
