### ISSUE TITLE
Tracking status of FDE (disk encryption)

### ISSUE THREAD

**Issue by sbe-arg** [Vanilla-OS/vanilla-installer#185]
### Feature Description

Issue to track the status of disk encryption.

### Rationale

Anyone using this OS on a laptop should use disk encryption nowdays.

**Comment by kbdharun** [comment]
Update on this: Disk Encryption has been added to [Albius](https://github.com/Vanilla-OS/Albius) (our Installer backend), the `albius` branch here in this repo (soon it will be merged into `main`, it will officially be available with Orchid. 

We already have an issue for this here https://github.com/Vanilla-OS/vanilla-installer/issues/102 so I am closing this one.
