### ISSUE TITLE
Unable to boot into installer or live environment

### ISSUE THREAD

**Issue by AverageBlank** [Vanilla-OS/vanilla-installer#189]
I am unable to boot into the installer or live environment.
I use a Nvidia GPU(Geforce GTX 1650). My CPU is AMD Ryzen 5 5600H.
I am also unable to boot into a virtualbox vm.
![image](https://github.com/Vanilla-OS/vanilla-installer/assets/112507212/3df273ac-d6b2-446a-a7dc-1f20d660a658)

**Comment by punky51** [comment]
having the issue it would not boot into live environment and i have a hybrid amd apu/nvidia dedicated

**Comment by AverageBlank** [comment]
Hey! I fixed the issue by re-downloading the ISO.
