### ISSUE TITLE
Selecting London as the time zone during a fresh install prevents Calendar from launching.

### ISSUE THREAD

**Issue by Photon101** [Vanilla-OS/vanilla-installer#213]
### Issue Description

The bug is reproducible on every fresh install using the r6 ISO on my machine. It can be fixed post-install by following the steps in the section below.

There seems to be two different time zones named London -- the one selected during install which isn't recognised by Calendar, and the one selected in Settings later on that **_is_** recognised by Calendar.

### Steps to Reproduce

- Select London as the time zone during the install process.
- After the first few reboots to complete installation, try to launch Calendar.
- Open Settings -> Date & Time, and note that the time zone is listed as "UTC (London...)".
- Switch the time zone to something else on the map, then immediately switch back to London.
- Note that the time zone is now listed as "GMT (London...)" instead of "UTC (London...)".
- Launching Calendar now works.

### On what version of Vanilla OS this happens?

22.10

**Comment by taukakao** [comment]
Possibly related to https://gitlab.gnome.org/GNOME/gnome-calendar/-/issues/740

**Comment by mirkobrombin** [comment]
Should have been fixed by https://github.com/Vanilla-OS/vanilla-installer/commit/0a9e59e08471d7f3dc35fedc177ec2ee47549a86
