### ISSUE TITLE
Vanilla OS is called Ubuntu in bios/uefi

### ISSUE THREAD

**Issue by RDKRACZ** [Vanilla-OS/vanilla-installer#217]

**Comment by mirkobrombin** [comment]
> > I think this is already addressed in Orchid with the new Albius backend.
> 
> If I'm not mistaken it's now just "grub", we should still change it to something else. From what I could find, this is done by adding the following line to `/etc/default/grub`:
> 
> ```
> GRUB_DISTRIBUTOR="Whatever we want"
> ```
> 
> Moving this to vanilla-installer since it's the most relevant place to add this configuration.

I am not sure after reading this https://www.gnu.org/software/grub/manual/grub/html_node/Simple-configuration.html

**Comment by axtloss** [comment]
> > I think this is already addressed in Orchid with the new Albius backend.
> 
> If I'm not mistaken it's now just "grub", we should still change it to something else. From what I could find, this is done by adding the following line to `/etc/default/grub`:
> 
> ```
> GRUB_DISTRIBUTOR="Whatever we want"
> ```
> 
> Moving this to vanilla-installer since it's the most relevant place to add this configuration.

It's not, the ID of grub in the uefi is set when installing grub with `grub-install`, the config file cannot change that.
If it's now only `grub`, it means that no ID is set while installing, to change it to something like `vanillaos`, we'd have to add the `--bootloader-id=vanillaos` flag

**Comment by matbme** [comment]
Latest alpha build should show up as `vanilla` in EFI.
