### ISSUE TITLE
Installer crashes randomly

### ISSUE THREAD

**Issue by full01n** [Vanilla-OS/vanilla-installer#259]
### Issue Description

Hi everyone, I'm trying the new Orchid ISO but the installer keeps crashing randomly; sometimes hangs before being able to click  on the first page, sometimes crashes when the disk partitioning is already in progress. Anyway I'm unable to install the OS (tried both VM and physical hardware)

### Steps to Reproduce

- Just boot the ISO and try to install

### On what version of Vanilla OS this happens?

Unreleased

**Comment by mirkobrombin** [comment]
Related https://github.com/Vanilla-OS/vanilla-installer/issues/254
