### ISSUE TITLE
[Orchid] Move down lists typing first letter druing installation process

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/vanilla-installer#261]
### Feature Description

When choosing languages, keyboard layout, we should scroll with mouse.
If I type P to go to Persian language, it does nothing.

### Rationale

Scrolling all alphabet is not fun. Once ok, twice or three time, it becomes bothering.

**Comment by Muqtxdir** [comment]
I feel that with: #248 #258 navigation would be much more easier compared to what you are describing

**Comment by Thatoo** [comment]
It could be yes, at least it will be better than what I tried this time

**Comment by mirkobrombin** [comment]
Refer to https://github.com/Vanilla-OS/vanilla-installer/pull/248 https://github.com/Vanilla-OS/vanilla-installer/pull/258

**Comment by Thatoo** [comment]
> I feel that with: #248 #258 navigation would be much more easier compared to what you are describing

It is great, I like that. Good job. This issue can be closed.
