### ISSUE TITLE
[Orchid] bash : /etc/bash_completion.d/apx: Permission denied 

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/vanilla-installer#263]
`apx completion bash --help `
is saying that to get autocompletion for every new session, I should run 
`apx completion bash  > /etc/bash_completion.d/apx`
I did and got this error : 
`bash : /etc/bash_completion.d/apx: Permission denied `

**Comment by mirkobrombin** [comment]
not related to the installer
