### ISSUE TITLE
Installer closes automatically 

### ISSUE THREAD

**Issue by HameezExE** [Vanilla-OS/vanilla-installer#271]
While trying to install the VanillaOS alpha builds (tested with the latest build too) the installer closes automatically normally within the first 30 seconds or few minutes never letting to install to finish. Happens when or not connected to internet. 

![20230828_230031.jpg](https://github.com/Vanilla-OS/vanilla-installer/assets/119889494/3fcf4046-c7b1-4e34-a4c6-f9c7c0653c04)

**Comment by mirkobrombin** [comment]
Keep tracking here https://github.com/Vanilla-OS/vanilla-installer/issues/276
