### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by minima1cha0s** [Vanilla-OS/vanilla-installer#274]
During the installatin moving the mouse outside the installer window to the right changes the mouse cursor to a right pointing arrow which does not reset.

VanillaOS-2-testing.20230829 in boxes

**Comment by acerspyro** [comment]
Cannot reproduce, is this still an issue?

**Comment by mirkobrombin** [comment]
I was never able to replicate

**Comment by taukakao** [comment]
I'm gonna close it. It can be reopened if it's still an issue.
