### ISSUE TITLE
Required disk space 

### ISSUE THREAD

**Issue by minima1cha0s** [Vanilla-OS/vanilla-installer#275]
I was trying out the alpha build - VanillaOS-2-testing.20230829 in boxes.
Typically I would assign 20GB disk space. 
I ran the installer and it prompted it requires 28 GB.
I assigned 30GB and ran again, this time it failed with out of space error in log.

Maybe a better estimate of how much space is required would be better.

**Comment by kbdharun** [comment]
We recently added LVM support to the installer and it is available in the latest alpha build 89 (and will be available in the future ones too). The new space/partition requirement is:

 - GPT partitioning table/scheme (in Device selection)
 - 1 GB (1024 MB) storage for Boot partition in `ext4` format.
 - 512 MB storage for EFI (System) partition in `fat32` format.
 - 20.5 GB (20992 MB) storage for the Root partition pool unformatted.
 - Optionally, create a Swap partition for hibernation support (we use `zram` by default).
 - The remaining storage should be used for the var partition in `btrfs` format. This partition is where all of your data is stored.

---

I am working on a new devlog, which will officially document all these requirements. This will make it into docs when we rewrite it in future.
