### ISSUE TITLE
install failed: error installing package

### ISSUE THREAD

**Issue by Mulkher** [Vanilla-OS/vanilla-installer#278]
The installer could not find the file grub-pc_2.06-2ubuntu12.1_amd64.deb on server http://archive.ubuntu.com

![Screenshot from 2023-09-13 09-42-37](https://github.com/Vanilla-OS/vanilla-installer/assets/144902567/e52434bc-68f4-4c72-bcea-ff687c4b4267)

**Comment by tobehn** [comment]
Probably you have to edit /etc/apt/sources.list and change the url to https://old-releases.ubuntu.com/ubuntu/
as the kenetic repos are not in https://archive.ubuntu.com/ubuntu/ anymore

**Comment by Mulkher** [comment]
The installation finished with no errors, but the system is not really usable. The software-store shows only a view apps. Downloaded flatpaks could not installed...
![Screenshot from 2023-09-15 12-17-31](https://github.com/Vanilla-OS/vanilla-installer/assets/144902567/b4a481a5-1d67-4981-a11c-dd88a884cc43)

**Comment by tobehn** [comment]
open console and run `vanilla-first-setup` - during the process it should ask for installing flatpak.

**Comment by Mulkher** [comment]
To verify the findings i have done an additional install. 
1. Before i install Vanilla OS i have to edit the file /etc/apt/sources.list
2. After Installation and rebooting the run of the Vanilla-First-Setup (as suggested, Pop-Up Window) doesn´t make sence. If i do so a correct installation does not happen. It runs, invites me to reboot and after rebooting it shows me a "Done!"-Windows. The "Finalizing"-Window is not shown.
3. Before running the Vanilla-First-Setup i have to edit the file /etc/apt/sources.list also on the installed system. Only if i open the console output during first-setup i could see the error, that the source path was wrong.
4. After editing and runing the first setup again everything is fine.

My suggestion:
- Please generate a new image file so that uninitiated users do not fall into this trap.
- If it is possible, catch the error with the wrong archive and show the error during first setup to the user.

**Comment by Mulkher** [comment]
add-on remark: Vanilla is a great distro, i love it.

**Comment by mirkobrombin** [comment]
In the next days we'll distribute an update fixing the problem, alongside with a new iso
