### ISSUE TITLE
bug: broken icon on initial panel

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/vanilla-installer#280]
## Intended behaviour

![Proposed](https://user-images.githubusercontent.com/54065734/261873606-4245adba-d222-47dd-b26d-edfac2fa95f4.png)

## Current behaviour

![Screenshot from 2023-09-18 12-21-47](https://github.com/Vanilla-OS/vanilla-installer/assets/26346867/bee16ca7-bc24-40e7-989f-4d441fb61870)

**Comment by Muqtxdir** [comment]
ideally ibelive the distro logo that is declared as distro info under the recipe should be used for this one.
