### ISSUE TITLE
No sleep during installation time

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/vanilla-installer#289]
The computer should not go to sleep during installation of Vanilla OS, not before the first reboot, nor after (before second reboot, before the reboot after user creation).

**Comment by Thatoo** [comment]
I keep experimenting that in the last version #84 .

**Comment by taukakao** [comment]
This was already fixed in the live-iso here: https://github.com/Vanilla-OS/live-iso/pull/345
