### ISSUE TITLE
Network setup with multiple NICs not possible

### ISSUE THREAD

**Issue by DragonHunter274** [Vanilla-OS/vanilla-installer#290]
My Mainboard has 2 seperate NICs and the installer wants both of them connected to proceed.
as a workaround I had to connect a second ethernet cable from the switch to the second NIC

**Comment by acerspyro** [comment]
Is this still an issue with Orchid?

**Comment by taukakao** [comment]
Probably still here by mistake, should've been fixed by https://github.com/Vanilla-OS/vanilla-installer/commit/c30e9495e1807f527af774e5e6b30a74cdd4f3d8

Can be reopened if not.
