### ISSUE TITLE
Blank SSID displayed in "Wireless Networks" section of the installer

### ISSUE THREAD

**Issue by michal-kurz** [Vanilla-OS/vanilla-installer#296]
My AP has SSID `Zazracna Kopulka <3`, but in the "wireless connection" list in the installer, its name appears blank. When I select the AP to connect to it, the name appears correctly:
![vanilla resized](https://github.com/Vanilla-OS/live-iso/assets/60649408/33a172cb-4c33-4bc4-81ad-14edd6b3aa0d) ![vanilla2 resized](https://github.com/Vanilla-OS/live-iso/assets/60649408/5c6eb2bc-065d-4ee3-adae-99261058946a)

other SSIDs are displayed correctly

---
Hardware: Dell XPS 9520
Build: [#80](https://github.com/Vanilla-OS/live-iso/actions/runs/6454386217)

**Comment by taukakao** [comment]
The SSID is rendered as markdown. You can make your SSID bold by setting it to `<b>Text</b>` which is pretty funny but still a bug.
