### ISSUE TITLE
Connecting to WIFI freezes the installer

### ISSUE THREAD

**Issue by michal-kurz** [Vanilla-OS/vanilla-installer#297]
Whenever I do the following, my installer freezes until reboot:
1. Select a network from then "Wireless networks" list and enter a password
2. Click "next" arrow in the installer

The installer is responsive until I click "next", then it freezes.
Clicking "next" while connected via ethernet cable works fine

---
Hardware: Dell XPS 9520
Build: [#80](https://github.com/Vanilla-OS/live-iso/actions/runs/6454386217)

**Comment by Cjnator38** [comment]
I've been dealing with the same thing on both my machines since build #77
