### ISSUE TITLE
installer crashes after a few seconds when using WiFi

### ISSUE THREAD

**Issue by rohmishra** [Vanilla-OS/vanilla-installer#301]
While starting installer using the latest build on VanillaOS-2-testing.20231015 / https://github.com/Vanilla-OS/live-iso/actions/runs/6526023055 the installer freezes and stops responding after a few seconds.

Annotation from Tau:
To work around this, use the system WiFi settings in the top right corner instead.

**Comment by taukakao** [comment]
Do you use wifi and did it happen after you entered your password?

**Comment by Huber1** [comment]
I have the same issue using version 116 from 3/2/2024.
This issue happens a few seconds after entering the wifi password.
I tried out guest wifi as well, happens there too (guest wifi has no mac filter).
No error message is shown.
In my case, the installer just closes and i am left with only the desktop background

**Comment by taukakao** [comment]
You could run:
Alt+F2
type `kgx` and press enter
then type `vanilla-installer` and type enter. 

It would be interesting if there is any output in the console after it crashes.

**Comment by Huber1** [comment]
For myself it worked now (I didn't change anything).
Maybe I'll install vanillaos later on another device, if it still happens then i'll report again.

**Comment by taukakao** [comment]
I can't reproduce it. But the installer logs:
`** (vanilla-installer:3632): CRITICAL **: 20:31:19.976: _get_ca_ignore_settings: assertion 'uuid && *uuid' failed`

after entering a WiFi password.

**Comment by rohmishra** [comment]
im out of town right now but will try recreating the issue once i return home. I remember discovering certificate issues in logs relating to system time as timesyncd wasnt configured and the time on a new hardware was out of date.

**Comment by taukakao** [comment]
Apparently, this bug still happens.

**Comment by taukakao** [comment]
@Bohne13 
Could you try using the wifi settings in the top right corner instead of the menu in the installer to set up your wifi? 
So after booting up, connect to the wifi through the top right corner and then proceed through the installer normally.

**Comment by Bohne13** [comment]
I did access the WiFi in the GNOME settings and started the 'vanilla-installer' with 'kgx'.

I could install VanillaOS (build nr. 120) without any problems!

So I'm only left with the problem how to use 'apx' to install Android Studio and Flutter ;D

**Comment by taukakao** [comment]
@Bohne13 Nice. 
And feel free to join the Discord for general support.

**Comment by taukakao** [comment]
![2024-04-27-20-07-42-023](https://github.com/Vanilla-OS/vanilla-installer/assets/44101694/0b740c7f-9a55-4c19-a9fb-b790e4d814cd)
This might be related

**Comment by taukakao** [comment]
Still happens in newest version

**Comment by jardon** [comment]
```
INFO:Installer::Window:Next page is 3
INFO:Installer::Window:Executing page's custom function
INFO:Installer::Window:Finished executing page's custom function
INFO:Installer::Window:(VanillaDefaultNetwork) Page is changing...
INFO:Installer::Window:(VanillaDefaultNetwork) It is not a final page
/usr/share/org.vanillaos.Installer/vanilla_installer/defaults/network.py:188: Warning: value "((GtkIconSize) 6)" of type 'GtkIconSize' is invalid or out of range for property 'icon-size' of type 'GtkIconSize'
  dialog = NMA4.WifiDialog.new(

** (vanilla-installer:20599): CRITICAL **: 23:41:02.977: _get_ca_ignore_settings: assertion 'uuid && *uuid' failed
**
nm:ERROR:../src/libnm-client-impl/nm-object.c:277:dispose: assertion failed: (!priv->client)
Bail out! nm:ERROR:../src/libnm-client-impl/nm-object.c:277:dispose: assertion failed: (!priv->client)
Aborted (core dumped)
```

**Comment by jardon** [comment]
If this is slowed down, the connection is actually successful.  NetworkManager runs a `dispose` function shown [here](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/3affccf29b53976a0cef5ea662f913d4913d44c8/src/libnm-client-impl/nm-object.c#L258) that fails an assertion.

**Comment by taukakao** [comment]
Yeah, this is definitely still happening

**Comment by coR2k** [comment]
Hello, thinkpad x13 gen 3 amd, MediaTek Wi-Fi® 6E RZ616 card, installer is crushing,
but if i'm using an usb ethernet card, it is ok.

**Comment by taukakao** [comment]
@coR2k 
Wait, did it open the settings for you or did it open just a small dialog with the password prompt for you?

**Comment by coR2k** [comment]
> @coR2k Wait, did it open the settings for you or did it open just a small dialog with the password prompt for you?

if I install the vanilla with Wi-Fi, the installer crashes 1-2 minutes after, 
if I install with ethernet, the installation finishes well

**Comment by taukakao** [comment]
@coR2k 
I know, but we recently changed the wifi connection method.

Did it open a small window with just the wifi or did it open the entire settings window?

**Comment by janekbt** [comment]
@taukakao I am in the same situation as @coR2k and it opened a small window with the password prompt and not the entire settings window.

**Comment by taukakao** [comment]
The newest version should just open the settings, preventing this bug.
I have to assume that you, @janekbt and @coR2k are using an older version.

**Comment by Yrlish** [comment]
I just downloaded the lastest iso and had this problem. Solved it by connecting to wifi in the top right system bar before starting to go through the wizard, as suggested earlier in this issue.

**Comment by taukakao** [comment]
@Yrlish 
Thank you, I have no idea how this happened but apparently I never actually made a PR for these changes. 
I'm very sorry for the confusion this has caused.

**Comment by Yrlish** [comment]
This also happened on the first boot wizard, it crashed when I tried to connect to wifi through it. So I connected in the system bar and then rebooted. After reboot I could get through the first boot wizard.
