### ISSUE TITLE
installer freezing in latest alpha

### ISSUE THREAD

**Issue by mcwimpy** [Vanilla-OS/vanilla-installer#303]
this is my 1st vanillaos attempt for development help. so i wanna try this VO2 of yours but after a couple of dozen attempts i'm quite sure, that i'm not doing anything wrong. i am using the #82 alfa that i dl'd from here. it' pretty much the same each time i try to install. i also watch the installer process and it is always on 0.0% after it freezes (which it does no matter how many times i click on `wait` ) ...

what i do is to start the live media, then click until i can set my Wifi data and connect to WLAN. mostly here already it will freeze, but in a handfull of times of those dozens of attempts, it will go forther to the languages and freeze there then.

i have a hp probook 6560b - let me know if i can further be of help.

p.s.: I watched these two bugs, and i find my issue is a bit of both.
https://github.com/Vanilla-OS/vanilla-installer/issues/259
https://github.com/Vanilla-OS/vanilla-installer/issues/297

edit: replaced backticks with apostrophes for better readability

**Comment by taukakao** [comment]
When entering a WiFi password, the installer will output:
`** (vanilla-installer:8096): CRITICAL **: 15:03.00.472: _get_ca_ignore_settings: assertion 'uuid && *uuid' failed`
