### ISSUE TITLE
[Orchid] Grub install failed

### ISSUE THREAD

**Issue by BSIT-Evanism** [Vanilla-OS/vanilla-installer#318]
After my third attempt, first is being stucked on the installer, this is now the latest error i got after the post install process began

Pc processor: amd athlon 200ge

Method used: Ventoy

![18d6cf7b-c0be-4b86-a192-f015f9f0d799.jpg](https://github.com/Vanilla-OS/vanilla-installer/assets/71175442/97658bd1-3331-4bbd-8616-c86d7247c215)

**Comment by axtloss** [comment]
You are using legacy bios, which vanilla os does not support, please switch to UEFI.
