### ISSUE TITLE
Output error if running with legacy BIOS

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/vanilla-installer#319]
Currently, this will just cause a weird error in the post steps.

Booting with legacy BIOS is still possible with things like Ventoy.

**Comment by Muqtxdir** [comment]
hi @taukakao 

would it make sense to have `vanilla-installer` do a check to make sure it is on UEFI capable device and then proceed to show the normal `vanilla-installer` and if not show a pretty error window saying unsupported. (_see below screenshot or what I mean_)

![image](https://github.com/Vanilla-OS/vanilla-installer/assets/54065734/07bb1d5d-dbb8-472b-99f2-420ec01f2a55)

**Comment by Muqtxdir** [comment]
also I think the strings could be better than the ones in screenshot, open for suggestions from others on that.

**Comment by taukakao** [comment]
@Muqtxdir 
I think it might make sense to suggest disabling legacy bios or csm mode. This is by far the more likely szenario here since UEFI has been around for ages.

I like the mockup.

**Comment by axtloss** [comment]
> I think it might make sense to suggest disabling legacy bios or csm mode. This is by far the more likely szenario here since UEFI has been around for ages.

it is not the only scenario that may happen and it could just confuse users more. Keeping it generic improves UX and makes no assumptions about the device.
