### ISSUE TITLE
[Orchid] No refs found for applications selected after second part of installation

### ISSUE THREAD

**Issue by BSIT-Evanism** [Vanilla-OS/vanilla-installer#324]
I tried to reinstall it one more time since it already happened to me where after the first part of installation, i would reboot into another part of installation to add the apps, I did the vso pico init command, waited for it to initialize then proceed with the application selection for second part then I reboot then greeted with the "no refs found" and no application found other than the apx, console, and other stuffs, no extensions, jo web, no libreoffice

![IMG_20231224_112328.jpg](https://github.com/Vanilla-OS/vanilla-installer/assets/71175442/973ec20f-7b7d-4b31-bbb0-b9c826dfc7a1)

**Comment by muhdsalm** [comment]
This is an issue with the First Setup app, not the Vanilla Installer.

**Comment by acerspyro** [comment]
Issue can be closed
