### ISSUE TITLE
If two network cards are connected, installers requires both to have internet access

### ISSUE THREAD

**Issue by msmafra** [Vanilla-OS/vanilla-installer#329]
Hello there,

I had this problem with the first alpha of VanillaOS Orchid, but then it wouldn't detect that my laptop's network card was connected. With the current ISO it detects correctly, but it doesn't advance the installation because my secondary network card, from my USB HUB, is not connected to the network. I connected both to check if it was the case and Voilà it worked!

**Comment by taukakao** [comment]
I'm assuming your internal network card just isn't fully supported and your external one is.

**Comment by axtloss** [comment]
> I connected both to check if it was the case and Voilà it worked!

Do you mean connected as in connected to a wifi network or connected as in physically connected to your laptop?

**Comment by msmafra** [comment]
> I'm assuming your internal network card just isn't fully supported and your external one is.

Not the case, worked with no problems with Vanilla OS 22.10 Kinetic. Both, actually.

**Comment by msmafra** [comment]
> > I connected both to check if it was the case and Voilà it worked!
> 
> Do you mean connected as in connected to a wifi network or connected as in physically connected to your laptop?

On the first alpha It wouldn't detect that the cable was even connected to my router, like no cable connected, this one it detects that my onboard one is connected but doesn't let me continue because the second one is not connected. As soon as I connect a cable to it the installation proceeds.

**Comment by taukakao** [comment]
> As soon as I connect a cable to it the installation proceeds

As soon as you plug in the USB Hub or as soon as you connect a network cable to the USB hub?

**Comment by msmafra** [comment]
> > As soon as I connect a cable to it the installation proceeds
> 
> As soon as you plug in the USB Hub or as soon as you connect a network cable to the USB hub?

The problem  is not detecting network connection, so network cable. 
If it doesn't detect network connection, it won´t continue, and in this case both cards must have network connection.

**Comment by taukakao** [comment]
So if you plug in the external one but don't plug anything into the internal one it doesn't work either?

**Comment by msmafra** [comment]
![vanilaosorchid01](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/9e8798a4-e490-42f6-973e-8a45df39ed73)
![vanilaosorchid02](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/a1bc58d7-8265-4658-9d9e-69ec999999cb)
![vanilaosorchid03](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/3cd3cb68-fc9c-43a8-af61-8d5f60fd7c9a)

**Comment by msmafra** [comment]
with 20240102 the same is happening

**Comment by taukakao** [comment]
Ahh, now I see what you mean. Yeah, this is definitely a bug.

**Comment by matbme** [comment]
Fixed by c30e949
