### ISSUE TITLE
Can't install and first I'm greeted with a not responding message

### ISSUE THREAD

**Issue by msmafra** [Vanilla-OS/vanilla-installer#345]
Hello there
Using the 20240122 image and I'm greeted with a "Vanilla OS Installer is not responding" message. After some seconds it show the installer behind it and it vanishes allowing me to continue with the installation; I'm able to set everything, but I doesn't finish.
I forgot to save the error log, I'll do it later.

![Screenshot from 2024-01-24 12-30-58](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/16739d3f-0984-426b-8042-0d01a8e0d33d)
![Screenshot from 2024-01-24 12-31-06](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/d93dbbe3-3b86-4559-8e69-7d6e93f04ca5)
![Screenshot from 2024-01-24 12-32-38](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/56319e5c-2c8e-49ca-8343-69186d1f5aa6)

**Comment by taukakao** [comment]
Could you please Force Quit the installer and then press `Alt + F2` and enter `kgx`
Then inside of there run vanilla-installer. 

Then please provide the output in that terminal window here.

**Comment by msmafra** [comment]
```
vanilla@vanillaos:~$ vanilla-installer
INFO:Installer::Builder:Performing display-condition: lspci | grep -i '.* nvidia .*'
INFO:Installer::Builder:Performing display-condition: grep 'hypervisor' /proc/cpuinfo
INFO:Installer::Builder:Step vm skipped due to display-conditions
INFO:Installer::Processor:processing the following final data: [{}, {'language': 'en_US.UTF-8'}, {'keyboard': {'layout': 'us', 'model': 'pc105', 'variant': ''}}, {}, {}, {'timezone': {'region': 'America', 'zone': 'Sao_Paulo'}}, {'nvidia': {'use-proprietary': True}}, {'disk': {'auto': {'disk': '/dev/sdb', 'pretty_size': '111.79 GB', 'size': 120034123264}}}, {'encryption': {'use_encryption': True, 'encryption_key': 'ExposedPassword'}}]

(vanilla-installer:4361): VTE-WARNING **: 20:28:39.161: (../src/vtepty.cc:810):void vte_pty_spawn_with_fds_async(VtePty*, const char*, const char* const*, const char* const*, const int*, int, const int*, int, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, int, GCancellable*, GAsyncReadyCallback, gpointer): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)



vanilla@vanillaos:~$ vanilla-installer
INFO:Installer::Builder:Performing display-condition: lspci | grep -i '.* nvidia .*'
INFO:Installer::Builder:Performing display-condition: grep 'hypervisor' /proc/cpuinfo
INFO:Installer::Builder:Step vm skipped due to display-conditions

(vanilla-installer:9385): Gtk-WARNING **: 20:30:15.500: GtkText - did not receive a focus-out event.
If you handle this event, you must return
GDK_EVENT_PROPAGATE so the default handler
gets the event as well
INFO:Installer::Processor:processing the following final data: [{}, {'language': 'en_US.UTF-8'}, {'keyboard': {'layout': 'us', 'model': 'pc105', 'variant': ''}}, {}, {}, {'timezone': {'region': 'America', 'zone': 'Sao_Paulo'}}, {'nvidia': {'use-proprietary': False}}, {'disk': {'auto': {'disk': '/dev/sdb', 'pretty_size': '111.79 GB', 'size': 120034123264}}}, {'encryption': {'use_encryption': False, 'encryption_key': ''}}]

(vanilla-installer:9385): VTE-WARNING **: 20:30:21.471: (../src/vtepty.cc:810):void vte_pty_spawn_with_fds_async(VtePty*, const char*, const char* const*, const char* const*, const int*, int, const int*, int, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, int, GCancellable*, GAsyncReadyCallback, gpointer): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
```

**Comment by taukakao** [comment]
Hm, I don't see anything particularly useful here. 

With what program did you flash the drive? Or did you use ventoy?

**Comment by msmafra** [comment]
> Hm, I don't see anything particularly useful here.
> 
> With what program did you flash the drive? Or did you use Ventoy?

Yes, using Ventoy. Don't flash my flashdrives anymore... at least not my fast ones. I'll flash it to another one to check.
Had problems only with Vanilla OS an Ubuntu 23.10 (non-legacy installer).

**Comment by taukakao** [comment]
Are you booting with UEFI or BIOS (including legacy mode or CSM)?
VanillaOS only supports UEFI

**Comment by msmafra** [comment]
> Are you booting with UEFI or BIOS (including legacy mode or CSM)? VanillaOS only supports UEFI

UEFI Only

**Comment by taukakao** [comment]
Trying out another USB Stick would be a good idea here.

**Comment by msmafra** [comment]
With balena etcher this was shown:

![Captura de tela de 2024-01-24 20-21-48](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/f5e68c32-5fbd-4aba-8454-d2e7b655c797)

Couldn't boot from the image even after flashing two different USB sticks (even my newest), 
including trying to see if the entries would appear in rEFInd (usually my last resort). I checked the ISO with shasum and reported OK.

Also remembered that Ventoy had/has a feature to load the ISO to the memory which solved some similar problems in the past, but also couldn't boot from it.

Is it using the same new Wizard/Installer as Ubuntu 23.10? I was only able to install Ubuntu 23.10 using the legacy installation ISO.

I'll let it be and try with one of the next new builds.

**Comment by muhdsalm** [comment]
Can you try again with the latest build and check if the issue still exists?

**Comment by msmafra** [comment]
Tried with the lastes available today. Etcher went with no warnings/errors, but I sill can´t install with the same "not responding" and the "Something went wrong" messages.

**Comment by muhdsalm** [comment]
The 'something went wrong message' comes _before_ the installer starts, or when you confirm the install?

**Comment by msmafra** [comment]
> The 'something went wrong message' comes _before_ the installer starts, or when you confirm the install?

I set everthing I need and click to start the installation. After 2-3 seconds it gives that message.

**Comment by muhdsalm** [comment]
Can you press 'show log' and tell me what it says?

**Comment by msmafra** [comment]
![Screenshot from 2024-02-27 13-54-10](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/a1c9933b-118c-46e6-b320-21575cbda932)
![Screenshot from 2024-02-27 13-54-17](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/60dec1dd-8b08-4a8b-bde4-1af199a03ad6)
![Screenshot from 2024-02-27 13-54-20](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/6e541cab-da78-4097-bd39-82521a887f17)
![Screenshot from 2024-02-27 13-54-23](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/5da6ce93-6f55-4b5a-acc2-dd80bd3aca36)
![Screenshot from 2024-02-27 13-54-28](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/376cdb56-b3d0-43fb-954d-f4bf0f383e53)
![Screenshot from 2024-02-27 13-54-34](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/b5ea91cc-f8dc-48ed-9ab6-2a017cb6cd2d)
![Screenshot from 2024-02-27 13-54-40](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/1351059c-1935-4692-9815-0e173303fe9f)
![Screenshot from 2024-02-27 13-54-58](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/0d915c18-1313-491f-98e9-c39d47275d97)
![Screenshot from 2024-02-27 13-55-14](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/07eb6509-58ac-4ea5-8b6b-1c33eeeea468)
![Screenshot from 2024-02-27 13-56-04](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/52270bb5-5055-4623-9d32-67a75081a439)
![Screenshot from 2024-02-27 13-57-26](https://github.com/Vanilla-OS/vanilla-installer/assets/1005457/eb61e4d4-9fd4-4527-9e82-1be5d28a52e9)


While capturing the screen this was the error and things were a bit different, meaning the network connection screen took a bit more time and the installation advanced a bit more. Why?! Dunno

```
Setup [1/20]: label
Setup [2/20]: mkpart
Creating filesystem with 262144 4k blocks and 65536 inodes
Filesystem UUID: 4f42e38e-cfe6-4401-a3ea-ec7dd0734992
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done

Setup [3/20]: mkpart
mkfs.fat 4.2 (2021-01-31)
Setup [4/20]: mkpart
Setup [5/20]: mkpart
Setup [6/20]: pvcreate
Setup [7/20]: pvcreate
Setup [8/20]: vgcreate
Setup [9/20]: vgcreate
Setup [10/20]: lvcreate
Setup [11/20]: lvm-format
Creating filesystem with 131072 4k blocks and 32768 inodes
Filesystem UUID: 593c1dc0-47e7-4fa5-95e7-a77fe14b77ae
Superblock backups stored on blocks: 
	32768, 98304

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

Setup [12/20]: lvcreate
Setup [13/20]: lvcreate
Setup [14/20]: make-thin-pool
Setup [15/20]: lvcreate-thin
Setup [16/20]: lvcreate-thin
Setup [17/20]: lvm-format
btrfs-progs v6.6.3
See https://btrfs.readthedocs.io for more information.

Performing full device TRIM /dev/vos-root/root-a (19.00GiB) ...
NOTE: several default settings have changed in version 5.15, please make sure
      this does not affect your deployments:
      - DUP for metadata (-m dup)
      - enabled no-holes (-O no-holes)
      - enabled free-space-tree (-R free-space-tree)

Label:              (null)
UUID:               8c84e78e-431e-435f-b85b-45631b5cab34
Node size:          16384
Sector size:        4096
Filesystem size:    19.00GiB
Block group profiles:
  Data:             single            8.00MiB
  Metadata:         DUP             256.00MiB
  System:           DUP               8.00MiB
SSD detected:       no
Zoned device:       no
Incompat features:  extref, skinny-metadata, no-holes, free-space-tree
Runtime features:   free-space-tree
Checksum:           crc32c
Number of devices:  1
Devices:
   ID        SIZE  PATH                
    1    19.00GiB  /dev/vos-root/root-a

Setup [18/20]: lvm-format
btrfs-progs v6.6.3
See https://btrfs.readthedocs.io for more information.

Performing full device TRIM /dev/vos-root/root-b (19.00GiB) ...
NOTE: several default settings have changed in version 5.15, please make sure
      this does not affect your deployments:
      - DUP for metadata (-m dup)
      - enabled no-holes (-O no-holes)
      - enabled free-space-tree (-R free-space-tree)

Label:              (null)
UUID:               a000d7aa-f0a0-4673-a5dd-58e6abee8845
Node size:          16384
Sector size:        4096
Filesystem size:    19.00GiB
Block group profiles:
  Data:             single            8.00MiB
  Metadata:         DUP             256.00MiB
  System:           DUP               8.00MiB
SSD detected:       no
Zoned device:       no
Incompat features:  extref, skinny-metadata, no-holes, free-space-tree
Runtime features:   free-space-tree
Checksum:           crc32c
Number of devices:  1
Devices:
   ID        SIZE  PATH                
    1    19.00GiB  /dev/vos-root/root-b

Setup [19/20]: lvcreate
Setup [20/20]: lvm-luks-format
panic: Timed out waiting for partition /dev/vos-var/var

goroutine 1 [running]:
github.com/vanilla-os/albius/core/disk.(*Partition).WaitUntilAvailable(0xc00020a2a0)
	github.com/vanilla-os/albius/core/disk/partition.go:343 +0xfc
github.com/vanilla-os/albius/core.runSetupOperation({0xc0004c7c38?, 0xc000068048?}, {0xc0004c7c40, 0xf}, {0xc000444a00, 0x4, 0x3?})
	github.com/vanilla-os/albius/core/recipe.go:598 +0x1b48
github.com/vanilla-os/albius/core.(*Recipe).RunSetup(0xc00045f360)
	github.com/vanilla-os/albius/core/recipe.go:629 +0x195
main.main()
	github.com/vanilla-os/albius/albius.go:20 +0x96
```
I tried again and got the original error I was having:

```
Setup [3/20]: mkpart
mkfs.fat 4.2 (2021-01-31)
Setup [4/20]: mkpart
Setup [5/20]: mkpart
Setup [6/20]: pvcreate
Setup [7/20]: pvcreate
panic: failed to run setup operation pvcreate: pvcreate: lvm.RunCommand: 
  Can't initialize physical volume "/dev/sde4" of volume group "vos-var" without -ff
  /dev/sde4: physical volume not initialized.


goroutine 1 [running]:
main.main()
	github.com/vanilla-os/albius/albius.go:22 +0x106
```

**Comment by msmafra** [comment]
This time no not responding messages and I used the same session for both tries.

**Comment by muhdsalm** [comment]
Seems like an issue with Albius.

**Comment by msmafra** [comment]
Tried #127 I wasn't able to install to any of my SSD via USB externally/docked. But, it installed on my internal NVMe, since I was about to do a fresh install of Fedora and some distros for testing. Something on the installed is not allowing it be installed via USB. At least on my machine.

**Comment by taukakao** [comment]
But since you were able to install on the internal drive I will mark this as completed

**Comment by msmafra** [comment]
> But since you were able to install on the internal drive I will mark this as completed

I did not try any of times before to install on my internal drive. Just installed now because of the opportune moment. So being able to install on my internal is not relevant here. In my opinion the problem persists.

**Comment by taukakao** [comment]
@msmafra 
Ok, but I think this issue has too many aspects to really count as one issue, though.
You're free to open a new issue with a specific error or problem you're facing.

**Comment by muhdsalm** [comment]
> > But since you were able to install on the internal drive I will mark this as completed
> 
> I did not try any of times before to install on my internal drive. Just installed now because of the opportune moment. So being able to install on my internal is not relevant here. In my opinion the problem persists.

Yes, the issue of not being able to install on removable drives exists and is being tracked at #348
