### ISSUE TITLE
Continue button doesn't work on Not Enough RAM page

### ISSUE THREAD

**Issue by RuriChoco** [Vanilla-OS/vanilla-installer#346]
![image](https://github.com/Vanilla-OS/vanilla-installer/assets/113755863/1ba7b0d3-be61-4a76-a1d8-1568032151d1)

This is my specs well some of it and my current os that i would dual boot
![image](https://github.com/Vanilla-OS/vanilla-installer/assets/113755863/bc85883f-f799-4b02-a871-70795089c92d)

When I try to install the newest aplha the 1/25/24 build on a 4gb machine I got an error or warning that it has not enough RAM and the continue button wont work.

**Comment by taukakao** [comment]
3731 MiB seems very unusual. It's roughly 3.9 GB or 3.6 GiB

I mean we could probably lower the requirement to 3.8 GB, but I'd rather make sure what the usual amount for a 4GB system is. 

The real problem here is that the Continue button doesn't work.

**Comment by RuriChoco** [comment]
Yah at least the continue button working it will be great 👍

**Comment by taukakao** [comment]
You can edit the file:
Press Alt+F2
type in kgx and press enter
```
sudo nano /usr/share/org.vanillaos.Installer/vanilla_installer/core/system.py
```

Change the 4 in the line that start with Systeminfo.ram to a 2.
After that just run vanilla-installer

**Comment by RuriChoco** [comment]
Nice thanks 👍

**Comment by RuriChoco** [comment]
My problem fix temporarily but I wish they could lower the requirements to a standard one and it would be a blast

**Comment by taukakao** [comment]
I think this is still an issue, so I'm gonna reopen this.

**Comment by SUFandom** [comment]
Happened also with mine, with this I am editing the squashfs, mod the setup then try packing them 
![2024-01-31-17-45-08-945](https://github.com/Vanilla-OS/vanilla-installer/assets/70519093/237987de-862a-4198-a16c-53eeac377e75)

Also @taukakao , the best limit is 3.6G because some units like mine reports 4GB, but has like 3.6GB as usable. (Ehem, some Chromebooks)

**Comment by muhdsalm** [comment]
> Is there any bypass command or I need to wait for a fix

Running `IGNORE_RAM=1 vanilla-installer` should work.
Anyways, I'm creating a PR for this issue, if it still doesn't work here's the bypass command for reference.

**Comment by mirkobrombin** [comment]
Closed by https://github.com/Vanilla-OS/vanilla-installer/commit/7a4e18fa7217a076f43e93fffa5b4a44876d1ad7
