### ISSUE TITLE
[Orchid BETA] Installer does not create a UEFI entry in BIOS

### ISSUE THREAD

**Issue by ParanoidNemo** [Vanilla-OS/vanilla-installer#350]
Here what happened:
I've a laptop with 2 SSD, one I use for windows 11 and one for Vanilla OS. I've installed the BETA on the SSD with the automatic partitioning, using the whole disk and on reboot my laptop booted straight into Windows. Entering the BIOS there is no boot entry for Vanilla OS but only the Windows one, I've created one manually and now it works.
I'd the same problem in the past with OpenSuse (all their different versions) but never with other distros (Debian, Arch, Fedora or previous version of Vanilla OS). On Suse the only way to fix it was manually partition and use the Windows EFI partition for the bootloader (which I would prefer not because I can killswitch the Windows SSD and still boot Vanilla OS if I've two different EFI partition).

Let me know if I can provide more info.

**Comment by SUFandom** [comment]
try removing the windows ssd, then try reinstalling it

**Comment by ParanoidNemo** [comment]
Sorry for the late reply, damn GitHub didn't send me a notification. I'll try and report back

**Comment by taukakao** [comment]
Probably duplicatd of #380
