### ISSUE TITLE
Installation costs much time

### ISSUE THREAD

**Issue by EraserAtGithub** [Vanilla-OS/vanilla-installer#353]
[Orchid]I am in China,2024/2/5 already installed for one day,I don't know what cause this,may network don't work well,or I don't have enough space?(/root setted 32GB,but it is full after the installation start)

**Comment by axtloss** [comment]
GitHub probably has slow connection speeds to china, if you have access to a working os could you install podman and run `podman pull ghcr.io/vanilla-os/core` to see how long that takes

**Comment by EraserAtGithub** [comment]
> GitHub probably has slow connection speeds to china, if you have access to a working os could you install podman and run `podman pull ghcr.io/vanilla-os/core` to see how long that takes

I used Orchid Live CD,

type /core:main.

Even though result is computer do not have enough space,but from about 12:30 to 15:30(UTC0),it pulled with high speed of 70KB/s.It only have one to archive,but console is full so I do not know others.

**Comment by axtloss** [comment]
Hm yeah that would mean that the github speed is very slow, sadly there isn't anything we can do about that

**Comment by taukakao** [comment]
It's depends on the day. Try again tomorrow ans see if it's better.
