### ISSUE TITLE
Check if installer still working when disk is full

### ISSUE THREAD

**Issue by EraserAtGithub** [Vanilla-OS/vanilla-installer#359]
Root Partition is settled for 32GB,it is full when installing,but I don't know why installer still working,the 'Github Pull' seems to end.
I have problem of installing for too long,so I doubt the reason is installer still working when disk is full

I don't know whether report a possible or stupid question is suit or not,I am sorry if I do this wrong

**Comment by muhdsalm** [comment]
Possibly an issue with Albius as opposed to the installer.

**Comment by EraserAtGithub** [comment]
I am stupid,it should be normal

**Comment by muhdsalm** [comment]
Maybe not? It may be useful to give an error.
