### ISSUE TITLE
#120 ISO-Build: Installer doesn't launch

### ISSUE THREAD

**Issue by Bohne13** [Vanilla-OS/vanilla-installer#365]
### Issue Description

After booting from an USB drive with the Iso image nr.120 I see a blank Gnome desktop.
There should be the installer GUI but nothing shows up.

### Steps to Reproduce

Install iso on USB drive.
Start the Laptop whit USB live image

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

Tried on an Asus Ultrabook

**Comment by Bohne13** [comment]
so without a change to yesterday, where I tried it twice. It worked to show the installer.
So this issue  may could be closed.

While trying to install VanillaOS the installer seems to exit/crash during installation.
At some point the window closes without any notice.
Maybe familiar with #363 

My first thought was, the installer finished the install and closed therefore (which still would not user friendly not noticing the user to safely reboot into the new install)

**Comment by taukakao** [comment]
@Bohne13 Are you using WiFi?

**Comment by Bohne13** [comment]
@taukakao yes!?

**Comment by taukakao** [comment]
@Bohne13 Then this is #301

**Comment by Bohne13** [comment]
okay, thanks for the support, I really excited to see a stable release this year!
I would close this issue due to duplication.
Hopefully #301 will be fixed soon!

**Comment by Bohne13** [comment]
Duplicate to #301

**Comment by Bohne13** [comment]
Duplicate to #301
