### ISSUE TITLE
open installer immediately with loading screen

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/vanilla-installer#366]
When starting the installer, it first runs some tasks like determining the GPU. 
This takes some time in which there is no window shown. This makes it hard for the user to know what's going on and also causes a "Not responding" warning in Gnome.

A better solution would be to open the Window immediately and show a "Setting up the installer" message or something.

**Comment by muhdsalm** [comment]
Is this still an issue after #405?

**Comment by taukakao** [comment]
You're right. This got resolved.
