### ISSUE TITLE
Panic creating LV during installation

### ISSUE THREAD

**Issue by TempsPerdu70** [Vanilla-OS/vanilla-installer#369]
Hi, got this during setup

panic:failed to run setup operation pvcreate:
  pvcreate: lvm.RunCommand:
  can't initialize physical volume "/dev/nvme0n1p10" of volume group "vos-root" without ff /dev/nvme0n1p10: physical volume not initialized

Thanks for all your work on the beta

**Comment by taukakao** [comment]
I decided to fix this in the frontend since it's not the job of Albius to manage lvm.
The removal of old lvm objects needs to be specified in the recipe.
