### ISSUE TITLE
label panic

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/vanilla-installer#370]
Trying to reinstall Vanilla OS (Orchid #117) on a disk of VM where Vanilla OS installation failed earlier ([because of encryption issue](https://github.com/Vanilla-OS/Albius/issues/47)) I get this error : 

> failed to label disk : Error : Partition(s) 4 on /dev/sda have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.

I have to delete the VM and remake one.

**Comment by taukakao** [comment]
This and #369 have the same cause
