### ISSUE TITLE
add option in the welcome page to remove vanilla

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/vanilla-installer#371]
Since users might not know how to handle LVM and such, it would be nice to have an option in the installer to uninstall VOS.

**Comment by axtloss** [comment]
The user shouldn't have to handle LVM either way, if a distro fails to install due to LVM existing then its the fault of the installer (yes, this also includes the vanilla installer). I dont think that it is worth the effort for something that is not really our fault.

**Comment by taukakao** [comment]
@axtloss 

I agree, I was thinking more about the scenario where a user would want to remove vanilla from a drive and turn it into a regular data drive.

**Comment by axtloss** [comment]
Then I believe it would be better to have a guide on how to remove the lvm volumes to turn a vanilla drive into a regular data drive, requiring people to install the iso and everything for something that can be done on pretty much every distro is too much effort (both for us and the user)

**Comment by taukakao** [comment]
good point
