### ISSUE TITLE
Can't install on empty drive

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/vanilla-installer#376]
This is most likely due to https://github.com/Vanilla-OS/vanilla-installer/commit/b1b14dea14d1feb3cfa2c6083c116a45c1e06872

Especially here: https://github.com/Vanilla-OS/vanilla-installer/blob/b1b14dea14d1feb3cfa2c6083c116a45c1e06872/vanilla_installer/utils/processor.py#L494

The `separate_device_and_partn` function needs the partition to exist. In manual partitioning, this can be assumed but in the `gen_install_recipe` with auto partitioning, this will fail if there is no partition with this name.

**Comment by taukakao** [comment]
It's probably best to get the disk name here: https://github.com/Vanilla-OS/vanilla-installer/blob/b1b14dea14d1feb3cfa2c6083c116a45c1e06872/vanilla_installer/utils/processor.py#L460-L467

**Comment by lukas-kasticky** [comment]
Fails with `lsblk: /dev/sda1: not a block device`

# Workaround

- Follow installation steps until…
- "Manual Partitioning"
    - Open GParted
    - "Device" → "Create Partition Table…" → `gpt`
    - "Partition" → "New" → File system: `ext4`
    - Apply All Operations
    - Close GParted
    - "Cancel"
- "Use entire disk"
- Install Vanilla OS
- Enjoy the Beta
