### ISSUE TITLE
Installer does not set EFI partition as ESP

### ISSUE THREAD

**Issue by fluoriteByte** [Vanilla-OS/vanilla-installer#380]
Installed vanilla OS this week and noticed a constant update that wouldnt apply on my laptop (lenovo v15 g2 alc), after trying the cli tool it told me that my ESP partition's bit wasnt set correctly
After going into gnome disks i manually changed the efi from "data base" to "ESP system", after a reboot that worked, and also i no longer had random times when the bios couldnt detect the efi (i thought i was a bios bug, but no

**Comment by taukakao** [comment]
The fix only seems to be for automatic partitioning, so I'm pretty sure this needs to also be added for manual partitioning.
