### ISSUE TITLE
increase minimum disk size

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/vanilla-installer#385]
The root needs 21 GB of space, the boot and efi partitions need 2 GB combined and the abroot cache usually takes up 8-15 GB in /var.
So without anything installed, we are at almost 40 GB. The vso container will also take up a bit of additional space.

I think the space requirement should be raised to at least 50 GB to guarantee a smooth experience.

**Comment by taukakao** [comment]
Implemented in #389

**Comment by kbdharun** [comment]
We probably need to update the website blog post to reflect the same.
