### ISSUE TITLE
An offline installer would benefit users with slow connectivity.

### ISSUE THREAD

**Issue by raphael-costa** [Vanilla-OS/vanilla-installer#402]
The US government has imposed sanctions on a third of all countries worldwide, with a notable impact on low-income nations. This trend has intensified over the past four administrations, peaking under President Biden, who enacted over 6,000 sanctions in just two years.

If you reside in a country affected by imperialist sanctions, you may face limitations like restricted high-speed internet access.

VanillaOS currently requires a substantial data download during installation. Some users might prefer the option to download an .iso image for a fully offline installation, allowing them to update the system at their convenience later on.

**Comment by taukakao** [comment]
Thanks for opening this issue. But this is already tracked here:
https://github.com/Vanilla-OS/live-iso/issues/301
