### ISSUE TITLE
can't install on laptop

### ISSUE THREAD

**Issue by osbyrne** [Vanilla-OS/vanilla-installer#403]
![image](https://github.com/user-attachments/assets/08766947-f850-4f23-afc5-eec9055811bb)

as you can see (don't mind the broken screen) the install has failed.
I've previously installed Ubuntu on this laptop with no issues.

what do

**Comment by Malix-off** [comment]
Please paste logs

**Comment by osbyrne** [comment]
I tried to install again and find logs, but the install succeeded.
This makes me more interested in immutability and watnot; surely some wicked moving parts would prevent a first install but allow a second try.

**Comment by taukakao** [comment]
@osbyrne 
The install process is in no way immutable. It's just a regular installer. 
When installed, the system is immutable.
