### ISSUE TITLE
In VM, the available keyboard names are compressed even with a high resolution screen (1440x900)

### ISSUE THREAD

**Issue by Francisco-Vivas** [Vanilla-OS/vanilla-installer#41]
When testing VanillaOS on a VM and trying to see all available keyboards types, the installer compresses the name even when the app is in full screen and is using a screen resolution of 1440x900.

## Expected Behavior
When the menu is opened and sufficient space is available, the full keyboard names available should be displayed correctly.

## Current Behavior
In a VM, the installer compress the available keyboard names when in full screen and using a resolution of 1440x900.

## Possible Solution
Dynamically increases the width of the menu of available keyboard names if we have enough space to display the full name.

## Steps to Reproduce
1. Open VanillaOS in a VM 
2. Set 1440x900 as resolution
3. Run the installer
4. Open the menu of available keyboard names

## Screenshot
![Screenshot from 2022-11-06 10-53-57](https://user-images.githubusercontent.com/37822420/200181498-dd13b4ab-c6b6-4285-bb39-74bc2506d93b.png)

**Comment by sherichev** [comment]
And i noticed that even in applications menu, the app names are compressed(under VirtualBox with FullHD res), maybe its related to GNOME itself, but its really annoying..
![VirtualBox_VanillaOS_06_11_2022_19_24_05](https://user-images.githubusercontent.com/83235068/200182625-367c4239-898e-4a86-b171-8824b9795aa4.png)

**Comment by mirkobrombin** [comment]
I think this is more a GTK thing then the vanilla-installer. I'll investigate thanks for reporting.
