### ISSUE TITLE
Next button is not immediately activated on language selection

### ISSUE THREAD

**Issue by pietrodicaprio** [Vanilla-OS/vanilla-installer#426]
After searching a language, on first selection the "next" button is not enabled:

![image](https://github.com/user-attachments/assets/ffd28ba6-27de-48e9-836c-d63ecf165d09)

it's required to select another language (to enable it) and then again the one you want.

**Comment by taukakao** [comment]
I can't reproduce this issue.

Could you please confirm that you are experiencing it in the latest version of the installer? @jardon

**Comment by jardon** [comment]
confirmed.

**Comment by taukakao** [comment]
ok, thanks
