### ISSUE TITLE
The selected keyboard layout doesn't stay after reboot

### ISSUE THREAD

**Issue by aolgh** [Vanilla-OS/vanilla-installer#43]
After installation, once the system has been rebooted, the system forgot which keyboard layout I had selected and just switched to the default US qwerty layout. This is on the unstable.20221106 iso, which (as far as I know) is the latest downloadable build.

**Comment by aolgh** [comment]
I don't know if this is related to gdm or vanilla os, but the login screen still uses the qwerty layout even if I change the keyboard layout in gnome settings.

**Comment by mirkobrombin** [comment]
This is fixed in the new installer



![Image](https://user-images.githubusercontent.com/9479903/209562223-9e68e31b-db4f-4a1d-a872-c44a00c75c5b.png)
