### ISSUE TITLE
Custom installation image URL validation rule incorrectly rejects certain domains

### ISSUE THREAD

**Issue by swety2003** [Vanilla-OS/vanilla-installer#433]
### Description
When attempting to use the custom installation image feature, I found that entering specific formats of URLs (e.g., `ghci.mirror.foo`) is incorrectly flagged as invalid by the current validation logic, preventing the installation process from continuing.

### Steps to Reproduce
1. Open the vanilla-installer application.
2. Navigate to the settings interface for specifying a custom installation image.
3. In the input field for the installation image URL, enter the following address: `ghci.mirror.foo/vanilla-os/desktop:main`.
4. Try to submit or confirm the input.

### Expected Result
The program should correctly identify the URL and allow the user to proceed with the installation process.

### Actual Result
The program displays an error message indicating that the entered URL format is incorrect and does not allow the operation to continue.

### Cause Analysis
By examining the source code, I found that the issue is due to an overly restrictive regular expression used in the validation logic:

```python
if self.image_url_entry.get_text() and re.match("^((?![a-z\\-]+\\.[a-z/\\-]+:.+).+)$", self.image_url_entry.get_text()) == None:

**Comment by axtloss** [comment]
The regex is fine, the issue is that it should be `!= None` instead of `== None`

**Comment by axtloss** [comment]
actually the regex is completely broken, it matches anything
