### ISSUE TITLE
Vanilla OS 2 Orchid latest version installation says something went wrong and a github link in the log

### ISSUE THREAD

**Issue by Mazushi-san** [Vanilla-OS/vanilla-installer#437]
Basically i start the installation, everything is okay but suddenly it says "Something went wrong" so i checked the log and there was some GitHub link and that was the last line

**Comment by taukakao** [comment]
This problem was just fixed. The new iso should be available from the vanilla page in about an hour or you can directly download it from here: https://github.com/Vanilla-OS/live-iso/actions/runs/11936173237

**Comment by taukakao** [comment]
If the new iso didn't fix the problem, feel free to reopen this issue.
