### ISSUE TITLE
Post install grub-mkconfig error

### ISSUE THREAD

**Issue by LucianoFilippucci** [Vanilla-OS/vanilla-installer#441]
Premise: in my computer I have, at the moment, 2 hdd's and 1 nvme:
- nvme with 2 partitions, 1 for Windows and the other for data

- 1.5TB hdd for data

- 500GB hdd where I want to install VanillaOS.

During the post install operations, on the step 9/23, grub-mkconfig it fails.

![PXL_20241122_094405517.RAW-01.MP.COVER.jpg](https://github.com/user-attachments/assets/9c8d9d29-270d-444d-9268-a85eea78d4c8)

![PXL_20241122_094345979.RAW-01.MP.COVER.jpg](https://github.com/user-attachments/assets/ca276e16-b560-4b3c-820a-8307aa442292)

![PXL_20241122_094355311.RAW-01.MP.COVER.jpg](https://github.com/user-attachments/assets/3397d36e-9431-4fef-b48d-6b62171c7c99)

![PXL_20241122_094400933.RAW-01.COVER.jpg](https://github.com/user-attachments/assets/297b891b-f35b-468e-99b2-498b48ed6d2e)

**Comment by taukakao** [comment]
This was fixed recently, please download the latest ISO.
