### ISSUE TITLE
continue automatically after manual partitioning

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/vanilla-installer#442]
After manually partitioning the drive, the user has to manually press the "to the right" button to continue. This is confusing, since it's different from the Automatic partitioning behavior, which immediately asks for confirmation.

**Comment by jardon** [comment]
whats perferred here? auto opening the confirmation dialog or just automatically moving to the next page?

**Comment by taukakao** [comment]
@jardon 
I think the confirmation dialog would be best here

**Comment by taukakao** [comment]
If the user accidentally selected the wrong partition, or if the installer would remove the wrong volume group or something the user could still catch it.
