### ISSUE TITLE
how can i fix this? 

### ISSUE THREAD

**Issue by Airmancooma** [Vanilla-OS/vanilla-installer#51]
I installed the github version because apx did not work and got this:

[INFO distinst:src/installer/steps/configure/chroot_conf.rs:154] disabling apt-cdrom from /etc/apt/sources.list
[INFO distinst:src/installer/steps/configure/chroot_conf.rs:56] removing packages: ["vanilla-installer", "gparted"]
[INFO distinst:crates/chroot/src/command.rs:103] running "chroot" "/tmp/distinst.nMlqTnnNtOb7" "apt-get" "purge" "-y" "vanilla-installer" "gparted"
[INFO distinst:crates/chroot/src/command.rs:93] Reading package lists...
[INFO distinst:crates/chroot/src/command.rs:93] Building dependency tree...
[INFO distinst:crates/chroot/src/command.rs:93] Reading state information...
[WARN distinst:crates/chroot/src/command.rs:93] E: Unable to locate package vanilla-installer
[INFO distinst:src/installer/steps/configure/chroot_conf.rs:370] creating recovery partition
[WARN distinst:src/installer/steps/configure/chroot_conf.rs:379] recovery at /tmp/distinst.nMlqTnnNtOb7/recovery was not found, therefore no recovery partition will be created
[ERROR distinst:src/installer/state.rs:37] configuring chroot error: error removing packages: command failed with exit status: exit status: 100
[ERROR distinst:src/installer/mod.rs:300] errored while installing system: error removing packages: command failed with exit status: exit status: 100

**Comment by mirkobrombin** [comment]
Wait for the next build please, I’m tracking this internally.
