### ISSUE TITLE
Strange behavior while pressing ENTER on Installing screen

### ISSUE THREAD

**Issue by alexgeraldo** [Vanilla-OS/vanilla-installer#65]
All tests were done using virtual machines. 
All the issues mentioned have been successfully replicated more than once on both VMware and Virtual Box.
Tested with RC build from 05/12/2022 (VanillaOS kinetic #55).

**Issues found:**
- When I manage to get to the "Installing..." screen, nothing happens. 
    - Nothing is logged. 
    - I left the VM in this state for more than 10 minutes and still nothing.
- On the second try something even stranger happened. Accidentaly I pressed ENTER key while on "Installing..." screen and it just jumped right into "All done" screen.
    - When I click "Show Log", nothing shows up.
    - I checked the VM and nothing was installed.

NOTE: Updated below. New terms to replicate the bugs.

Including screenshots from "Not installing" and the "All done screen when pressed ENTER".

![Installing-nothing](https://user-images.githubusercontent.com/67390786/205642868-b795c12f-c292-4358-82df-1879b947725f.png)

![All-done-enter-pressed](https://user-images.githubusercontent.com/67390786/205642860-6a0620a8-d074-4b5f-ada5-2094491129b0.png)

**Comment by alexgeraldo** [comment]
UPDATE:

- Apparently if you allow the installation to go all the way through in Virtual Box, VanillaOS installs successfully. Probably a problem with VMware.
- The bug of clicking ENTER still happens in both, however it is only possible to replicate sometime during the beginning of the installation (or even before starting), at some point in the installation process it is no longer possible to click ENTER to reach the "All done" page " earlier.

**Comment by mirkobrombin** [comment]
Related https://github.com/Vanilla-OS/vanilla-installer/issues/62

**Comment by alexgeraldo** [comment]
There is a problem with the VM's yes, but I would put more emphasis on the fact that when you press ENTER (early during installation) it causes the installation to automatically terminate. I think it's more important than the VM issue. And I think it's also an easy problem to solve.

Below is a video that shows how an accidental double click on the ENTER key can cause the OS not to install.
https://youtu.be/HnkYa8bj6is

**Comment by mirkobrombin** [comment]
> There is a problem with the VM's yes, but I would put more emphasis on the fact that when you press ENTER (early during installation) it causes the installation to automatically terminate. I think it's more important than the VM issue. And I think it's also an easy problem to solve.
> 
> Below is a video that shows how an accidental double click on the ENTER key can cause the OS not to install. (First ENTER to start the installation and the second one end installation immediately.) https://youtu.be/HnkYa8bj6is

Sure, that's why I've mentioned the related issue.
