### ISSUE TITLE
Searching for a keyboard layout changes it in process

### ISSUE THREAD

**Issue by delight-aug** [Vanilla-OS/vanilla-installer#81]
When you start typing "English" in the search field, it activates each layout it thinks is the best match, making the search an interesting challenge.

![image](https://user-images.githubusercontent.com/51861383/210021885-5ffea49d-5d9d-4feb-8834-286ec5fae62b.png)

**Comment by mskf1383** [comment]
I had same problem. When I tryed to search for "persian", after typing "per", the layout set to Esperanto and I became unable to type the remained charectars of "persian".

**Comment by mirkobrombin** [comment]
fixed some releases ago
