### ISSUE TITLE
Manual partitioning/dual boot

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/vanilla-installer#86]
Manual partitioning and dual boot are currently unsupported due to ABRoot complexity. We are managing to implement it and will be available in the near future.

**Comment by Necross220** [comment]
Roger that

**Comment by Oliver4code** [comment]
Yes. So much needed this feature. Please add this feature as soon as possible!

**Comment by MentorToc** [comment]
Will it be possible to encrypt a single partition? For example, /home only. For many people this plays a crucial role when choosing a system. I'm talking about luks or luks2.

**Comment by GabsEdits** [comment]
> can I install a previous version that support the manual partition and then update to latest ?
> is this possible to do it this way ?

VanillaOS never had Manual Partitioning

**Comment by GabsEdits** [comment]
> > > can I install a previous version that support the manual partition and then update to latest ?
> > > is this possible to do it this way ?
> > 
> > VanillaOS never had Manual Partitioning
> 
> It was present in Alpha, Beta builds before we switched to ABRoot from Almost. But that builds wouldn't get repo updates as we switched from GitHub to launchpad after it.

Yea, but it was never in a stable version

**Comment by kbdharun** [comment]
> Yea, but it was never in a stable version

Yep

**Comment by muhdsalm** [comment]
Is it possible to get an ETA for when this issue will be resolved (Given that a pull request has been linked)?

**Comment by kbdharun** [comment]
> Is it possible to get an ETA for when this issue will be resolved (Given that a pull request has been linked)?

@matbme is working on it, with an initial PR now. As mentioned in #dev , the optimistic timeline would be r8 or 23.04.
