### ISSUE TITLE
Installer appears to be unable to partition the drive

### ISSUE THREAD

**Issue by vatsjijj** [Vanilla-OS/vanilla-installer#89]
It appears that the installer is not able to partition my drive, as every installation attempt ends in failure with the following error:
```
not enough partitions found for block device 'sda' with mountpoint '/' and size '20479999488'
```
That is the only error output I appear to get.
After this error the installer does nothing and only hangs out on the `Installing...` screen. There is no console output and nothing has visibly gone wrong on the GUI end, yet in the terminal it has visibly failed.
This has been a consistent error yet I am unsure if it is reproducible for any other systems as I only have one machine to test Vanilla on.
If it helps to further diagnose the issue, my machine has two SSDs (1 NVMe and 1 SATA SSD), so _maybe_ that could be a potential hiccup with the installer?

**Comment by mirkobrombin** [comment]
Try erasing the disk with gparted and start the installer again

**Comment by vatsjijj** [comment]
> Try erasing the disk with gparted and start the installer again 

I forgot to specify that I've already attempted to install on a blank disk (erased) and manually partition the drive. It seems to error no matter what I do.

**Comment by mirkobrombin** [comment]
I mean, try without manual partitioning the disk

**Comment by vatsjijj** [comment]
So here is the list of things that I have attempted:
- Install on a already partitioned drive
- Wipe the drive and retry
- Manually partition and retry
- Wipe the drive and reboot, then retry
- Manually partition, reboot, then retry
None of which have made any progress. I'm kind of stumped here considering that nobody else seems to have this problem.
If it helps, it actually starts with
```
INFO:Installer::Processor:post_installation process started
INFO:Installer::Processor:getting root partitions
```
And then it attempts to locate the partitions, of which it cannot because it hasn't partitioned the drive in the first place.
What is especially strange to me is how it begins with the _post installation_ phase first, instead of doing the pre-installation process. I know that can't be right so I'm curious at what may be going awry here.

**Comment by Radical4ever** [comment]
Since we cannot install it from the installer, is there a manual way to do this until it gets fixed?

**Comment by mirkobrombin** [comment]
Tried again on both bare, vm (legacy), vm (uefi) and it works as expected. I need some info (idk which info).

**Comment by Radical4ever** [comment]
> Tried again on both bare, vm (legacy), vm (uefi) and it works as expected. I need some info (idk which info).

My disk is a Gigabyte ssd with linux mint installed, maybe that could help a little, or maybe trying to burn the image to the usb with a different program (like rufus)

**Comment by Radical4ever** [comment]
> Since we cannot install it from the installer, is there a manual way to do this until it gets fixed?

Again, is there any other way for now?

**Comment by Radical4ever** [comment]
> > Tried again on both bare, vm (legacy), vm (uefi) and it works as expected. I need some info (idk which info).
> 
> My disk is a Gigabyte ssd with linux mint installed, maybe that could help a little, or maybe trying to burn the image to the usb with a different program (like rufus).
> 
> Other thing that could be is the bios/efi parameters, maybe that could help?

**Comment by Radical4ever** [comment]
Tried using another usb stick but that didnt work too

**Comment by pidement** [comment]
I has a similar problem, and on my case a **workaround** is avoid to select the region as `America/Argentina/Buenos_aires`. Sounds very weird, but I can reproduce the error only if I select that region. Maybe the workaround works for you.

---

Error when I run the installer from a terminal:
```
runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
INFO:Installer::Processor:post-installation process started
INFO:Installer::Processor:getting root partitions
INFO:Installer::Processor:finding partitions for block device '/dev/nvme0n1' with mountpoint '/' and size '20479999488'
!!! An error occurred while running post_install script.
 Share the following error with the developers:
 not enough partitions found for block device 'nvme0n1' with mountpoint '/' and size '20479999488'
```
My laptop:
```
Host: GS66 Stealth 10UG REV:1.0
CPU: Intel i9-10980HK (16) @ 5.300GHz
GPU: NVIDIA GeForce RTX 3070 Mobile / Max-Q 
GPU: Intel CometLake-H GT2 [UHD Graphics] 
Memory: 2971MiB / 31916MiB
```
lsblk:
```
NAME       MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0        7:0    0   1.4G  1 loop /rofs
sda          8:0    1  14.3G  0 disk 
├─sda1       8:1    1  14.3G  0 part 
│ └─ventoy 253:0    0   1.7G  1 dm   /cdrom
└─sda2       8:2    1    32M  0 part 
zram0      252:0    0  15.6G  0 disk [SWAP]
nvme0n1    259:0    0 953.9G  0 disk 
```

**Comment by vatsjijj** [comment]
I'll have to try this later, but maybe the installer doesn't like it when you select the correct time zone? This error happens when I select `America/New_York` so it would be curious if not selecting that fixed it.

**Comment by Radical4ever** [comment]
I can confirm that changing the region from argentina/buenos_aires to another one worked and the installer is working fine!

**Comment by Oliver4code** [comment]
> So here is the list of things that I have attempted:
> 
> * Install on a already partitioned drive
> * Wipe the drive and retry
> * Manually partition and retry
> * Wipe the drive and reboot, then retry
> * Manually partition, reboot, then retry

How did you do manually partition!? This option is not available yet!

**Comment by vatsjijj** [comment]
> > So here is the list of things that I have attempted:
> > 
> > * Install on a already partitioned drive
> > * Wipe the drive and retry
> > * Manually partition and retry
> > * Wipe the drive and reboot, then retry
> > * Manually partition, reboot, then retry
> 
> How did you do manually partition!? This option is not available yet! 

The installer and Vanilla have a certain partition structure, I followed that manually via GParted.

**Comment by kbdharun** [comment]
Hi, can you check if this issue is prevalent when manually partitioning the drives in the installer in the recent release?
