### ISSUE TITLE
Installer remains after install

### ISSUE THREAD

**Issue by swanux** [Vanilla-OS/vanilla-installer#95]
When I boot the installed system, the installer opens the same way it does in the live environment after boot, and it remains on the system.

**Comment by mirkobrombin** [comment]
This is weird. Can you provide output for `sudo abroot get present`?

**Comment by swanux** [comment]
Present root partition is b

**Comment by mirkobrombin** [comment]
I'm not sure how this is possible because the environment where the system is installed is clean but I don't rule it out. Please uninstall it manually for now.

**Comment by swanux** [comment]
Okay I've done it

**Comment by pupss89345** [comment]
It is haappen to me 
Please tell me how to unistall it manually ??
I can't find any where can remove it

**Comment by mirkobrombin** [comment]
I tested it this morning and the installer was not there. Idk why this happen to some users. Which ISO is it? R5?

To remove it: `sudo abroot apt remove vanilla-installer`

**Comment by swanux** [comment]
I've encountered it with the first release, maybe will try a reinstall with the latest one (wanna try anyway starting a fresh one) and I'll report back here

**Comment by swanux** [comment]
Okay. Did a fresh install with the R5 ISO and the installer indeed is removed as expected. (Also, it's nice to see the improvements, it feels a lot more polished already).

_(There was another issue though which caught my attention on the first run, but I'll open a separate feed for that as it's completely unrelated)._
